{{- if .Values.general.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fedimint.serviceAccountName" . }}
  labels:
    {{- include "fedimint.labels" . | nindent 4 }}
  {{- with .Values.general.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.general.serviceAccount.automount }}
{{- end }}
