apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guardian-ui.fullname" . }}
  labels:
    {{- include "guardian-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "guardian-ui.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "guardian-ui.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: fedimint
                  app.kubernetes.io/instance: {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: guardian-ui
          image: "{{ .Values.guardianui.image.repository }}:{{ .Values.guardianui.image.tag }}"
          imagePullPolicy: {{ .Values.guardianui.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.guardianui.service.port }}
          env:
            - name: PORT
              value: {{ .Values.guardianui.service.port | quote }}
            - name: REACT_APP_FM_CONFIG_API
              value: {{ .Values.fedimintd.config.fm_api_url | quote }}
              #value: ws://fedimint-mutinynet:8174