apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fedimint.fullname" . }}
  labels:
    {{- include "fedimint.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.fedimintd.storage.accessModes | quote}}
  resources:
    requests:
      storage: {{ .Values.fedimintd.storage.storage | quote}}
  {{- if .Values.fedimintd.storage.storageClassName }}
  storageClassName: {{ .Values.fedimintd.storage.storageClassName | quote }}
  {{- end }}