apiVersion: v1
kind: Service
metadata:
  name: {{ include "fedimint.fullname" . }}
  labels:
    {{- include "fedimint.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fedimintd.service.type }}
  ports:
    - name: fedimintd-p2p
      port: 8173
      targetPort: 8173
      protocol: TCP
    - name: fedimintd-api
      port: 8174
      targetPort: 8174
      protocol: TCP
  selector:
    {{- include "fedimint.selectorLabels" . | nindent 4 }}
