apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fedimint.fullname" . }}
  labels:
    {{- include "fedimint.labels" . | nindent 4 }}
spec:
  serviceName: "{{ include "fedimint.fullname" . }}"
  replicas: 1
  selector:
    matchLabels:
      {{- include "fedimint.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.fedimintd.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fedimint.labels" . | nindent 8 }}
        {{- with .Values.fedimintd.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fedimint.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.fedimintd.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.fedimintd.securityContext | nindent 12 }}
          image: "{{ .Values.fedimintd.image.repository }}:{{ .Values.fedimintd.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.fedimintd.image.pullPolicy }}
          ports:
            - name: fedimintd-p2p
              containerPort: {{ .Values.fedimintd.service.p2p.port }}
              protocol: TCP
            - name: fedimintd-api
              containerPort: {{ .Values.fedimintd.service.api.port }}
              protocol: TCP
          {{ if .Values.fedimintd.probes.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.fedimintd.service.api.port }}
            initialDelaySeconds: {{ .Values.fedimintd.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.fedimintd.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.fedimintd.probes.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.fedimintd.probes.liveness.timeoutSeconds }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.fedimintd.service.api.port }}
            initialDelaySeconds: {{ .Values.fedimintd.probes.readiness.initialDelaySeconds }}
            failureThreshold: {{ .Values.fedimintd.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.fedimintd.probes.readiness.successThreshold }}
            timeoutSeconds: {{ .Values.fedimintd.probes.readiness.timeoutSeconds }}
          {{ end }}
          env:
            - name: RUST_LOG
              value: "debug"
            - name: FM_BITCOIN_RPC_KIND
              value: {{ .Values.fedimintd.config.fmBitcoinRpcKind }}
            - name: FM_BITCOIN_RPC_URL
              value: {{ .Values.fedimintd.config.fmBitcoinRpcUrl }}
            - name: FM_BITCOIN_NETWORK
              value: {{ .Values.fedimintd.config.fmBitcoinNetwork }}
            - name: FM_BIND_P2P
              value: {{ printf "0.0.0.0:%d" (int .Values.fedimintd.service.p2p.port) | quote }}
            - name: FM_P2P_URL
              value: {{ .Values.fedimintd.config.fmP2pUrl }}
            - name: FM_BIND_API
              value: {{ printf "0.0.0.0:%d" (int .Values.fedimintd.service.api.port) | quote }}
            - name: FM_API_URL
              value: {{ .Values.fedimintd.config.fmApiUrl }}
          volumes:
            - name: fedimintd-data
              persistentVolumeClaim:
                claimName: {{ include "fedimint.fullname" . }}
          {{- with .Values.fedimintd.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.fedimintd.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
          {{ toYaml .Values.fedimintd.resources | nindent 12 }}