apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.gatewayd.storage.accessModes | quote}}
  resources:
    requests:
      storage: {{ .Values.gatewayd.storage.size | quote}}
  {{- if .Values.gatewayd.storage.storageClassName }}
  storageClassName: {{ .Values.gatewayd.storage.storageClassName | quote }}
  {{- end }}