apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gatewayd.service.type }}
  ports:
    - name: api
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
