apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  serviceName: "{{ include "gateway.fullname" . }}"
  replicas: 1
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.gatewayd.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gateway.labels" . | nindent 8 }}
        {{- with .Values.gatewayd.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.gatewayd.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.gatewayd.securityContext | nindent 12 }}
          image: "{{ .Values.gatewayd.image.repository }}:{{ .Values.gatewayd.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gatewayd.image.pullPolicy }}
          ports:
            - name: gatewayd-api
              containerPort: {{ .Values.gatewayd.service.api.port }}
              protocol: TCP
          {{ if .Values.gatewayd.probes.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.gatewayd.service.api.port }}
            initialDelaySeconds: {{ .Values.gatewayd.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.gatewayd.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.gatewayd.probes.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.gatewayd.probes.liveness.timeoutSeconds }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.gatewayd.service.api.port }}
            initialDelaySeconds: {{ .Values.gatewayd.probes.readiness.initialDelaySeconds }}
            failureThreshold: {{ .Values.gatewayd.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.gatewayd.probes.readiness.successThreshold }}
            timeoutSeconds: {{ .Values.gatewayd.probes.readiness.timeoutSeconds }}
          {{ end }}
          args:
            - gatewayd
            - lnd
          env:
            - name: RUST_LOG
              value: debug
            - name: FM_GATEWAY_API_ADDR
              value: {{ .Values.gatewayd.config.fmGatewayApiAddr | quote }}
            - name: FM_GATEWAY_DATA_DIR
              value: /gateway_data
            - name: FM_GATEWAY_FEES
              value: {{ .Values.gatewayd.config.fmGatewayFees | quote }}
            - name: FM_GATEWAY_LISTEN_ADDR
              value: 0.0.0.0:80
            - name: FM_GATEWAY_PASSWORD
              value: {{ .Values.gatewayd.config.fmGatewayPassword | quote }}
            - name: FM_LND_MACAROON
              value: /lnd_secrets/admin.macaroon
            - name: FM_LND_RPC_ADDR
              value: {{ .Values.gatewayd.config.fmLndRpcAddr | quote }}
            - name: FM_LND_TLS_CERT
              value: /lnd_secrets/tls.cert
            {{- range .Values.gatewayd.additionalEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - mountPath: /lnd_secrets
              name: gateway-lnd-secrets
              readOnly: true
          {{- with .Values.gatewayd.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.gatewayd.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
          {{ toYaml .Values.gatewayd.resources | nindent 12 }}
      volumes:
        - name: gatewayd-data
          persistentVolumeClaim:
            claimName: {{ include "gateway.fullname" . }}
        - name: gateway-lnd-secrets
          secret:
            secretName: gateway-lnd-secrets